name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - conda-cpp-build
      - conda-cpp-tests
      - conda-python-build
      - conda-python-tests
      - docs-build
      - wheel-build-cpp
      - wheel-build-python
      - wheel-tests
      - devcontainer
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@pull-request/230
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@pull-request/230
    with:
      enable_check_generated_files: false
  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-build.yaml@pull-request/230
    with:
      build_type: pull-request
  conda-cpp-tests:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@pull-request/230
    with:
      build_type: pull-request
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@pull-request/230
    with:
      build_type: pull-request
  conda-python-tests:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@pull-request/230
    with:
      build_type: pull-request
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@pull-request/230
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:latest"
      run_script: "ci/build_docs.sh"
  wheel-build-cpp:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@pull-request/230
    with:
      matrix_filter: group_by([.ARCH, (.CUDA_VER|split(".")|map(tonumber)|.[0])]) | map(max_by(.PY_VER|split(".")|map(tonumber)))
      build_type: pull-request
      script: ci/build_wheel_cpp.sh
  wheel-build-python:
    needs: wheel-build-cpp
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@pull-request/230
    with:
      build_type: pull-request
      script: ci/build_wheel_python.sh
  wheel-tests:
    needs: wheel-build-python
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@pull-request/230
    with:
      build_type: pull-request
      script: ci/test_wheel.sh
  devcontainer:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@pull-request/230
    with:
      arch: '["amd64"]'
      cuda: '["12.2"]'
      build_command: |
        sccache -z;
        build-all -DBUILD_BENCHMARKS=ON --verbose;
        sccache -s;
